# Generated by Django 5.2.16 on 2026-07-20 10:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512, verbose_name='ФИО')),
                ('phone_numbers', models.TextField(verbose_name='Номера телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('priority', models.IntegerField(default=0, verbose_name='Приоритет')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('contacts', models.ManyToManyField(blank=True, related_name='clients', to='core.contactperson', verbose_name='Контактные лица')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь Django')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('number', models.CharField(max_length=16, verbose_name='Номер (пр. 1234-56)')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрыт')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='objects', to='core.client', verbose_name='Заказчик')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='core.objectstatus', verbose_name='Состояние объекта')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название изделия')),
                ('part_name', models.CharField(blank=True, max_length=255, verbose_name='Название части')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('payment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Оплата')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.object', verbose_name='Объект')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Количество')),
                ('status', models.CharField(choices=[('queued', 'В очереди'), ('in_progress', 'В процессе изготовления'), ('completed', 'Готов')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_items', to='core.employee', verbose_name='Работник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.product', verbose_name='Изделие')),
            ],
        ),
    ]
