# Generated by Django 5.2.16 on 2026-07-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParsingBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение в чёрном списке')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_number',
            field=models.CharField(default=0, max_length=32, verbose_name='Номер изделия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.RemoveField(
            model_name='object',
            name='status',
        ),
        migrations.AlterField(
            model_name='object',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='object',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='objects', to='core.objectstatus', verbose_name='Состояние объекта'),
        ),
    ]
