# Generated by Django 5.2.16 on 2026-07-21 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parsingblacklist_product_product_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_objects', to='core.client', verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='object',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='linked_objects', to='core.objectstatus', verbose_name='Состояние объекта'),
        ),
    ]
