# Generated by Django 5.2.16 on 2026-07-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_object_client_alter_object_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_number']},
        ),
    ]
