# Generated by Django 5.2.16 on 2026-08-16 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='status',
        ),
        migrations.AddField(
            model_name='object',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_objects', to='core.objectstatus', verbose_name='Состояние объекта'),
        ),
    ]
