from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('master', views.master_dashboard, name='master_dashboard'),
    path('master/import/', views.import_objects_view, name='import_objects'),
    path('master/object/<str:hashed_id>/',
         views.object_detail_view, name='object_detail'),
    path('master/object/<int:object_id>/toggle-status/',
         views.toggle_object_status_view, name='toggle_object_status'),
    path('master/object/<int:object_id>/delete/',
         views.delete_object_view, name='delete_object'),
    path('master/product/<int:product_id>/assign/',
         views.assign_worker_view, name='assign_worker'),
    path('master/item/<int:item_id>/complete/',
         views.complete_product_item, name='complete_product_item'),
    path('master/items-in-work/', views.items_in_work,
         name='items_in_work'),
    path('employee/', views.employee_dashboard, name='employee_dashboard'),
    path('employee/item/<int:item_id>/start/',
         views.start_queued_item, name='start_queued_item'),
    path('employee/product/<int:product_id>/start/',
         views.start_product_item, name='start_product_item'),
    path('employee/items/', views.employee_items, name='employee_items'),
    path('item/<int:item_id>/cancel/',
         views.cancel_product_item, name='cancel_product_item'),
]
